### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION jdns_sd.dll

### ISSUE THREAD

**Issue by mikeburon** [ETCLabs/mDNSWindows#3]
Hello and thanks for any help.
While migrating my app to JAVA 11 I found an issue and can't fix it.
I seem to be having an EXCEPTION_ACCESS_VIOLATION in jdns_sd.dll using the java classes. 

I have attached the generated dump file.

It seems to be related with the call to the function com.apple.dnssd.AppleService.BlockForData() but can't find the exact problem.

[hs_err_pid30668.log](https://github.com/ETCLabs/mDNSWindows/files/4042028/hs_err_pid30668.log)

**Comment by samkearney** [comment]
Hi @mikeburon, I think you've found the wrong repository. This a targeted fork of Bonjour which focuses specifically on the C API on Windows. The Java code has been removed from this fork and is not built here. I recommend you ask this question on the relevant Apple support forum. Thanks!
